# boolean-datetime (W1502)

*Using datetime.time in a boolean context.* Using datetime.time in a
boolean context can hide subtle bugs when the time they represent
matches midnight UTC. This behaviour was fixed in Python 3.5. See
<a href="https://bugs.python.org/issue13936"
class="reference external">https://bugs.python.org/issue13936</a> for
reference. This message can't be emitted when using Python \>= 3.5.
